language: java

services:
- mysql

before_install:
- mysql --user=root --host=localhost -e "CREATE DATABASE IF NOT EXISTS geouserdb;" 
- cd ServerGeoUserGradle
- chmod +x gradlew
- ./gradlew cleanBuildCache

jdk: oraclejdk8

notifications:
  email: false
  
after_script:
- cat /home/travis/build/Pas21/geo-user-project/ServerGeoUserGradle/build/findbugsReports/main.html