language: java

services:
- mysql

before_install:
- cd ServerGeoUserGradle
- chmod +x gradlew

jdk: oraclejdk8

notifications:
  email: false
  
after_script:
- cat /home/travis/build/Pas21/geo-user-project/ServerGeoUserGradle/build/findbugsReports/main.html
- cat /home/travis/build/Pas21/geo-user-project/ServerGeoUserGradle/build/reports/tests/test/index.html