language: java

services:
- mysql

sudo: true

before_install:
- echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
- wget https://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
- sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
- sudo apt-get update -q
- sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
- sudo mysql_upgrade
- sudo apt-get update -y
- sudo service mysql restart
- cd ServerGeoUserGradle
- chmod +x gradlew
- ./gradlew clean
 


jdk: 
- oraclejdk8

notifications:
  email: false
  
after_script:
- cat /home/travis/build/Pas21/geo-user-project/ServerGeoUserGradle/build/findbugsReports/main.html
- cat /home/travis/build/Pas21/geo-user-project/ServerGeoUserGradle/build/reports/JUnitReport/index.html
#Setting MySQL Configuration in Travis CI
- cat ~travis/.my.cnf


sudo: required
dist: trusty
group: deprecated-2017Q4