language: java

services:
- mysql

before_install: 
- cd ServerGeoUserGradle
- chmod +x gradlew
- ./gradlew clean

jdk: oraclejdk8

notifications:
  email: false
  
after_script:
- cat /home/travis/build/Pas21/geo-user-project/ServerGeoUserGradle/build/findbugsReports/main.html